import { readFileSync } from "node:fs";
import type {
    HeaderField,
    HttpMessage,
    ParsedSignature,
    SignatureInput,
} from "../src/types.js";

/** Read committed fixture bytes without trimming or normalizing line endings. */
export function fixtureBytes(name: string): Buffer {
    return readFileSync(new URL(`./fixtures/rfc9421/${name}`, import.meta.url));
}

function headerLines(lines: readonly string[]): HeaderField[] {
    return lines.map((line) => {
        const separator = line.indexOf(": ");
        if (separator < 1) throw new Error("Invalid test fixture header");
        return [line.slice(0, separator), line.slice(separator + 2)];
    });
}

/**
 * Only decodes the fixed RFC textual request representation, not RFC 9421
 * signature syntax. The committed source file uses LF, not HTTP wire CRLF.
 */
export function rfcRequest(): HttpMessage {
    const text = fixtureBytes("request-head.txt").toString("ascii");
    const [requestLine, ...lines] = text.split("\n");
    if (requestLine !== "POST /foo?param=Value&Pet=dog HTTP/1.1") {
        throw new Error("Unexpected RFC request fixture");
    }
    return {
        kind: "request",
        request: {
            method: "POST",
            targetUri: "https://example.com/foo?param=Value&Pet=dog",
            rawRequestTarget: "/foo?param=Value&Pet=dog",
            httpVersion: "1.1",
            headers: headerLines(lines),
        },
    };
}

/** Published header bytes, not headers generated by agentsig's signer. */
export function rfcSignatureHeaders(): HeaderField[] {
    return headerLines(fixtureBytes("signature-headers.txt").toString("ascii").split("\n"));
}

/**
 * Independent expected structure transcribed from RFC 9421 B.2.6.
 * Never obtain this expectation by running the implementation under test.
 * Return fresh objects so mutation tests cannot contaminate other test cases.
 */
export function rfcSignatureInput(): SignatureInput {
    return {
        label: "sig-b26",
        components: [
            { name: "date", parameters: [] },
            { name: "@method", parameters: [] },
            { name: "@path", parameters: [] },
            { name: "@authority", parameters: [] },
            { name: "content-type", parameters: [] },
            { name: "content-length", parameters: [] },
        ],
        parameters: [
            ["created", { kind: "integer", value: 1618884473 }],
            ["keyid", { kind: "string", value: "test-key-ed25519" }],
        ],
    };
}

/** Independent verification input: no agentsig parsing or signing involved. */
export function rfcParsedSignature(): ParsedSignature {
    return {
        input: rfcSignatureInput(),
        signature: Uint8Array.from(fixtureBytes("signature.bin")),
    };
}